---
code_indent: "  "
collections:
  api:
    output: true
    permalink: "/:collection/:path/"
    title: API
    tab-order: 1
  examples:
    output: true
    permalink: "/:collection/:path/"
    title: Examples
    tab-order: 2
  guides:
    output: true
    permalink: "/:collection/:path/"
    title: Guides
    tab-order: 3
exclude:
  - _tasks
  - build
  - docs
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - programming-pages.gemspec
  - Rakefile
  - README.md
  - screenshot.png
highlighter: rouge
permalink: pretty
plugins:
  - jemoji
project:
  name: "{project_name}"
  owner: "{project_owner}"
  repo: "{project_repo}"
  version: "{project_version}"
sass:
  style: compressed
template_version: 0.5.7
example_root: "/examples"
guide_root: "/guides"
module_root: "/api"
