---
project:
  name: programming pages
  owner: pixeldroid
  repo: https://github.com/pixeldroid/programming-pages
  version: 0.5.11
attributions:
  entypo-pictograms: Daniel Bruce
  font-awesome: Dave Gandy
  glyphicon-halflings: Jan Kovařík
  jquery: https://github.com/jquery/jquery
  jquery-address: https://github.com/Semantic-Org/Semantic-UI-Docs/blob/master/server/files/javascript/library/history.js
  loadcss: https://github.com/filamentgroup/loadCSS
  monokai-colors: Wimer Hazenberg
  mousetrap: https://craig.is/killing/mice
  semantic-ui: https://github.com/Semantic-Org/Semantic-UI
  svg-icon: https://leungwensen.github.io/svg-icon/
collections:
  guides:
    output: true
    permalink: "/:collection/:path/"
    title: Guides
    tab-order: 1
  examples:
    output: true
    permalink: "/:collection/:path/"
    title: Examples
    tab-order: 2
  layout_api:
    output: true
    permalink: "/:collection/:path/"
    title: Layout API
    tab-order: 3
code_indent: "  "
highlighter: rouge
kramdown:
  footnote_backlink: "⮌"
permalink: pretty
sass:
  style: compressed
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: pixeldroid/programming-pages
