---
code_indent: "  "
collections:
  layout_api:
    output: true
    permalink: "/:collection/:path/"
    title: Layout API
  examples:
    output: true
    permalink: "/:collection/:path/"
    title: Examples
  guides:
    output: true
    permalink: "/:collection/:path/"
    title: Guides
highlighter: rouge
permalink: pretty
plugins:
- jemoji
project:
  name: programming pages
  owner: pixeldroid
  repo: https://github.com/pixeldroid/programming-pages
  version: 0.5.2
sass:
  style: compressed
template_version: 0.5.2
example_root: "/examples"
guide_root: "/guides"
module_root: "/api"
