---
code_indent: "  "
collections:
  guides:
    output: true
    permalink: "/:collection/:path/"
    title: Guides
    tab-order: 1
  examples:
    output: true
    permalink: "/:collection/:path/"
    title: Examples
    tab-order: 2
  layout_api:
    output: true
    permalink: "/:collection/:path/"
    title: Layout API
    tab-order: 3
highlighter: rouge
permalink: pretty
plugins:
- jemoji
project:
  name: programming pages
  owner: pixeldroid
  repo: https://github.com/pixeldroid/programming-pages
  version: 0.5.4
sass:
  style: compressed
template_version: 0.5.4
example_root: "/examples"
guide_root: "/guides"
module_root: "/layout_api"
